Name:           ros-indigo-husky-bringup
Version:        0.1.2
Release:        0%{?dist}
Summary:        ROS husky_bringup package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/husky_bringup
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-husky-base
Requires:       ros-indigo-husky-description
Requires:       ros-indigo-imu-filter-madgwick
Requires:       ros-indigo-imu-transformer
Requires:       ros-indigo-lms1xx
Requires:       ros-indigo-microstrain-3dmgx2-imu
Requires:       ros-indigo-nmea-comms
Requires:       ros-indigo-nmea-navsat-driver
Requires:       ros-indigo-robot-localization
Requires:       ros-indigo-robot-upstart
Requires:       ros-indigo-tf
Requires:       ros-indigo-um6
Requires:       scipy
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-roslaunch

%description
Clearpath Husky installation and integration package

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Thu Feb 12 2015 Paul Bovbel <pbovbel@clearpathrobotics.com> - 0.1.2-0
- Autogenerated by Bloom

* Fri Jan 30 2015 Paul Bovbel <pbovbel@clearpathrobotics.com> - 0.1.1-0
- Autogenerated by Bloom

* Tue Jan 13 2015 Paul Bovbel <pbovbel@clearpathrobotics.com> - 0.1.0-0
- Autogenerated by Bloom

